# Generated by Django 2.2 on 2020-06-09 14:45

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200609_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='文章正文'),
        ),
    ]
